server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cs;MODE=MySQL;DB_CLOSE_DELAY=-1;;
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true